### ISSUE TITLE
Update peer dependencies pls.

### ISSUE THREAD

**Issue by steida** [gaearon/react-document-title#12]
I just runned into "Two Reacts Won’t Be Friends" issue just by removing `import React from 'react'` from component using react-document-title.

Btw, isn't better to remove peerDependencies at all?

**Comment by steida** [comment]
And for https://github.com/gaearon/react-side-effect as well.

**Comment by gaearon** [comment]
There is no problem with peer dependencies in this project. It specifies `>= 0.11.0` which includes `0.13`.
If install is failing, some other project is blocking it. NPM is unhelpful in that it lists all peerdeps, not just the one that failed.
