### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by anjdreas** [gaearon/react-document-title#16]
Sorry for the newbie question, but I'm having trouble getting this running.

I've run `npm install --save react-document-title` 

Then I tried
`require('../../node_modules/react-document-title/index.js')` from my `main.js` file, then use webpack or browserify to create a `bundle.js` and link that in instead of the main.js file, but it says **Uncaught ReferenceError: DocumentTitle is not defined** in my JSX file.

I see that the bundle is loaded in the browser, and I can see the react-document-title code in the bundle, but it's not available to my JSX for some reason. It's probably a rookie mistake, but I'm stumped. Hope you can give any pointers.

Cheers

Example source code:

index.html
```html
    <script src="https://fb.me/react-with-addons-0.13.3.js"></script>
    <script src="https://fb.me/JSXTransformer-0.13.3.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react-router/0.13.3/ReactRouter.min.js"></script>
    <script src="~/src/js/bundle.js"></script>
    <script type="text/jsx" src="~/Content/lib/jsx/main.jsx"></script>
```

main.js
```
'use strict'

var DocumentTitle = require('../../node_modules/react-document-title/index.js');
```

main.jsx
```jsx
var Router = ReactRouter;
var DefaultRoute = Router.DefaultRoute;
var Link = Router.Link;
var Route = Router.Route;
var RouteHandler = Router.RouteHandler;

var App = React.createClass({
    render: function() {
        return (
            <DocumentTitle title='Home'>
                <this.props.activeRouteHandler />
                <div id="wrapper">
                </div>
            </DocumentTitle>
        );
    }
});
```

**Comment by gaearon** [comment]
Why do you have two separate `main.js` and `main.jsx` files? You should `require` the `DocumentTitle` in the file where it is being used:

```js
var Router = ReactRouter;
var DefaultRoute = Router.DefaultRoute;
var Link = Router.Link;
var Route = Router.Route;
var RouteHandler = Router.RouteHandler;

var DocumentTitle = require('react-document-title');

var App = React.createClass({
    render: function() {
        return (
            <DocumentTitle title='Home'>
                <this.props.activeRouteHandler />
                <div id="wrapper">
                </div>
            </DocumentTitle>
        );
    }
});
```

**Comment by gaearon** [comment]
To clarify, CommonJS modules do not put globals onto the `window`. Executing the `index.js` from the library will not make a global `DocumentTitle` available. Instead, you need to use the return value of the `require` function.

There is also another potential problem in your configuration. If you want to use an NPM package, it's best if you use React Router and React from NPM as well. Otherwise you need to tell Webpack that they are global with `externals` config option, or your bundle will include two Reacts: one from document title dependency, and one from the script in your HTML file.

I suggest you use everything from NPM instead.

**Comment by anjdreas** [comment]
Thank you for the thorough explanation, that was very helpful. Got it all working now :-)

**Comment by gaearon** [comment]
Sure, feel free to come back with questions. :-)
