### ISSUE TITLE
Want to use this module in server, and want to ask

### ISSUE THREAD

**Issue by ericfong** [gaearon/react-document-title#17]
according to this line
https://github.com/gaearon/react-document-title/blob/master/index.js#L6

It seems to me that the _serverTitle is singleton for whole server. isn't it?

**Comment by gaearon** [comment]
It is, but it's not a problem because it is cleared every time you call `DocumentTitle.rewind()`.

**Comment by ericfong** [comment]
concurrency http call?

**Comment by BinaryMuse** [comment]
@ericfong `React.renderToString` is synchronous, so just call `DocumentTitle.rewind()` right after.

**Comment by ericfong** [comment]
You are right. Thanks a lot

**Comment by bbnnt** [comment]
Humm… sorry to bother right here. It works very well on the client, but nothing happens when used server side (in express). The title in the source remains unchanged. Or shouldn't I expect it to behave "isomorphically" ?

**Comment by gaearon** [comment]
@bbnnt On the server side it's up to you to call `DocumentTitle.rewind()` to actually get the title string and insert it into your HTML response.

**Comment by bbnnt** [comment]
@gaearon yep I'm looking around - this helped https://github.com/gaearon/react-document-title/issues/7#issuecomment-68894067, I wasn't wrapping around the handler :/
```
let content = React.renderToString(
<ReactDocumentTitle>
<Handler />
 </ReactDocumentTitle>
);
var title = ReactDocumentTitle.rewind();
```
