### ISSUE TITLE
emitting '<noscript></noscript>' to DOM

### ISSUE THREAD

**Issue by goldensunliu** [gaearon/react-document-title#20]
```
React = require('react'),
DocumentTitle = require('react-document-title');
var Component = React.createClass({
      render: function () {
        return React.createElement(DocumentTitle, {title: 'irrelevant'} );
      }
});

var markup = React.renderToStaticMarkup(React.createElement(Component));
```

this is a slightly modified logic of https://github.com/gaearon/react-document-title/blob/master/test/common.js#L9.

it is emitting '<noscript></noscript>' as its markup. 

I assume it is a bug since we are claiming in README.md that it doesn't emit anything to DOM

**Comment by gaearon** [comment]
I'm a bit confused, is it returning `''` or `<noscript>`? In any case, this is because you have nothing inside `<DocumentTitle>`. It's meant to wrap other components.

**Comment by goldensunliu** [comment]
@gaearon, oops yeah I meant the noscript tag. totally valid point on its intent a component wrapper. Will close. 

Ps.  What would have to change to render '' if we used it on its own without being a wrapper?

**Comment by gaearon** [comment]
Hmm, not sure, sorry!
