### ISSUE TITLE
React 0.14 compatibility

### ISSUE THREAD

**Issue by romanenko** [gaearon/react-document-title#25]
If we could tag a new version at [react-side-effect](https://github.com/gaearon/react-side-effect) and sync new version in this lib's dependencies, we would have this great tiny library support React 0.14 with the help of recently merged [pull-request](https://github.com/gaearon/react-side-effect/commit/5b18f192e1577baeaaa4b8e02f5403ab10b4bd14)

**Comment by gaearon** [comment]
Done. Sorry for delays.
