### ISSUE TITLE
As high order component

### ISSUE THREAD

**Issue by srph** [gaearon/react-document-title#26]
Initial idea:

```es6
@title(props => `${props.user.name}'s page`)
class SomeComponent extends Component {
}
```

Has its downsides. One obvious example:

```es6
// works
class SomeComponent extends Component {
  render() {
    return (
      <DocumentTitle title={`{this.state.user}'s profile`}>
        ..
      </DocumentTitle>
    );
  }
}

// won't work in the proposed api
@title(...)
class SomeComponent extends Component {
  render() {
    return (
      ..
    );
  }
}
```

But this doesn't happen very happen often, and I don't think it should. See [Smart and Dumb Components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0).

Would send a PR if this is okay.

---

Awesome work by the way, @gaearon!

**Comment by gaearon** [comment]
How about we change export to have two named exports: `Title` (component) and `title` (HOC)?

**Comment by srph** [comment]
That's a good idea. But IMO, new people coming to this library could get confused (maybe? :confused:).

**Comment by gaearon** [comment]
I'll close because I'm fairly satisfied with existing API and I don't want to have two ways to do the same thing.

**Comment by cooperka** [comment]
Posting my working HOC example because Google sent me to this issue:

```jsx
import DocumentTitle from 'react-document-title';
import { compose, getDisplayName, setDisplayName } from 'recompose';

// HOC to set the document title from any page.
export function withDocumentTitle(title) {
  return (Component) => {
    const Enhanced = (props) => (
      <DocumentTitle title={title}>
        <Component {...props} />
      </DocumentTitle>
    );

    return compose(
      setDisplayName(getDisplayName(Component)),
    )(Enhanced);
  };
}
```

Usage:

```jsx
const WelcomePage = /* ...your component... */;
export default withDocumentTitle('Welcome')(WelcomePage);
```
