### ISSUE TITLE
Not work in iphone wechat

### ISSUE THREAD

**Issue by bravemantonyzheng** [gaearon/react-document-title#29]
It can not work properly in iphone wechat.

Below is my code.

```javascrpt
// routes.jsx
export default (
  <Route>
    <Route path="/" component={ App }>
      <Route path="dailyoperation" component={ DailyOperation } />
    </Route>
    <Route path="/test1" component={ Test1 }/>
    <Route path="/test2" component={ Test2 }/>
    <Route path="/test3" component={ Test3 }/>
  </Route>
);
```

```javascript
// Test2.jsx

import React, { Component, PropTypes } from 'react';
import DocumentTitle from 'react-document-title';
import { Link } from 'react-router';

class Test2 extends Component {
  render() {
    return (
      <DocumentTitle title="test2">
      <div>
        test2 <Link to="/test3">test3</Link>
      </div>
      </DocumentTitle>
    );
  }
}

export default Test2;
```

I test in In iphone5,6 wechat browser, the title does't change when i switch in different page.

**Comment by gaearon** [comment]
Check out the source code. All we do is set `document.title`. If it doesn't work for you, it probably means that `document.title` is not supported in your environment, or that you forgot to add `<DocumentTitle>` to other route handlers such as `Test1` and `Test3`. This doesn't appear to be an issue with this project.

**Comment by zhouzefei** [comment]
my version is 2.0.2
i have the same issue. it does not work in iphone , but is ok on android .
