### ISSUE TITLE
Memory leak on server side!

### ISSUE THREAD

**Issue by ludoblues** [gaearon/react-document-title#36]
Rendering this module on the server side generate a memory leak!

**Comment by gaearon** [comment]
Please help fix it? 😉

**Comment by ludoblues** [comment]
Yep i'll try to take some time to investigate, this is not so easy to localise ^^

**Comment by leebenson** [comment]
@ludoblues - do you have any more info on this? This is after calling `DocumentTitle.rewind()`, right?

**Comment by ludoblues** [comment]
We stopped using it, i'll reopen if i can reproduce it.

**Comment by leebenson** [comment]
ok, thanks @ludoblues. Out of interest, what do you use instead? If there's a memory leak, it's likely that hints at a problem with the underlying [react-side-effect](https://github.com/gaearon/react-side-effect) library, so it'd be useful to know whether this was simply a case of omitting `DocumentTitle.rewind()` or whether there's a genuine memory leak somewhere.

**Comment by ludoblues** [comment]
@leebenson Yes we invoked DocumentTitle.rewind(), we are using Helmet instead, which also use react-side-effect. I didn't notice any memory leak.

I'll try to replace Helmet by react-document-title the week to see how it goes, i'll reopen if i notice something wrong!

**Comment by leebenson** [comment]
Thanks @ludoblues
