### ISSUE TITLE
Expand support and rename project

### ISSUE THREAD

**Issue by simenbrekken** [gaearon/react-document-title#5]
I've been using react-document-title for an isomorphic project and quickly discovered that most of the pages that are being rendered on the server could use generated metadata such as description and [Open Graph](http://ogp.me).

I'm proposing renaming the project to `react-document-metadata` and expand usage to arbitrary props in addition to title:

```jsx
<Metadata
  title="My fine page"
  opengraph={{image: this.state.image.url}}
  description={this.getDescription()} />
```

Naturally only title would be read by the browser for updating `window.title` but it could also be expanded to support things like dynamic favicons.

Thoughts?

**Comment by Nevon** [comment]
Just wanted to echo a request for this. I'm doing server rendering for a site with lots of products, and it would be great to be able to add, for example, og tags from react.

**Comment by gpbl** [comment]
@Nevon I'm looking into it these days.

**Comment by gaearon** [comment]
Keep us posted!

**Comment by kellyrmilligan** [comment]
I'm still pretty new to react, so for my project for now I went with a mixin approach. 

see this gist:
https://gist.github.com/kellyrmilligan/405fb66a2195c4a20732

not sure if it helps with this. 

I am doing server rendering as well, so for initial page load I have a handlebars template that uses the same data structure to spit out the tags.

**Comment by gaearon** [comment]
I have an idea about how we can do all of that without renaming the project or expanding the API.
Give me a few hours..

**Comment by gpbl** [comment]
Oh good ! I've yet to work on it (just came out from the whole isomorphic stuff)

**Comment by gaearon** [comment]
The idea is to split the component:

### DocumentTitle.js

```js
'use strict';

var React = require('react'),
    Children = require('react/addons').Children,
    PropTypes = React.PropTypes,
    BubbleMixin = require('./BubbleMixin');

var DocumentTitle = React.createClass({
  displayName: 'DocumentTitle',

  mixins: [BubbleMixin],

  statics: {
    rewind: function () {
      var activeInstance = this.getActiveInstance();
      this.clearMountedInstances();

      if (activeInstance) {
        return activeInstance.props.title;
      }
    }
  },

  propTypes: {
    title: PropTypes.string
  },

  getDefaultProps: function () {
    return {
      title: ''
    };
  },

  performSideEffect: function () {
    var title = this.props.title;
    if (typeof document !== 'undefined' && title !== document.title) {
      document.title = title;
    }
  }
});

module.exports = DocumentTitle;
```

### BubbleMixin.js (better names welcome)

```js
'use strict';

var React = require('react'),
    Children = require('react/addons').Children,
    PropTypes = React.PropTypes;

var BubbleMixin = {
  statics: {
    clearMountedInstances: function () {
      this.mountedInstances = [];
    },

    getMountedInstances: function () {
      if (!this.mountedInstances) {
        this.mountedInstances = [];
      }

      return this.mountedInstances;
    },

    getActiveInstance: function () {
      var mountedInstances = this.getMountedInstances();
      if (mountedInstances.length > 0) {
        return mountedInstances[mountedInstances.length - 1];
      }
    },

    performSideEffectOnActiveInstance: function () {
      var activeInstance = this.getActiveInstance();
      if (activeInstance) {
        activeInstance.performSideEffect();
      }
    }
  },

  isActiveInstance: function () {
    return this === this.constructor.getActiveInstance();
  },

  componentWillMount: function () {
    var mountedInstances = this.constructor.getMountedInstances();
    mountedInstances.push(this);

    this.constructor.performSideEffectOnActiveInstance();
  },

  componentDidUpdate: function (prevProps) {
    if (this.isActiveInstance()) {
      this.constructor.performSideEffectOnActiveInstance();
    }
  },

  componentWillUnmount: function () {
    var mountedInstances = this.constructor.getMountedInstances(),
        index = mountedInstances.indexOf(this);

    mountedInstances.splice(index, 1);
    this.constructor.performSideEffectOnActiveInstance();
  },

  render: function () {
    if (this.props.children) {
      return Children.only(this.props.children);
    } else {
      return null;
    }
  }
};

module.exports = BubbleMixin;
```

Put `BubbleMixin` into an NPM module, make it a dependency. It's trivial to implement any kind of “prop bubbling” on top of it so we can make `react-meta` or whatever without complicating this project.

**Comment by gaearon** [comment]
https://github.com/gaearon/react-document-title/pull/8

**Comment by gpbl** [comment]
Loving the idea, cleaner code and a mixin with a funny name :+1:

Trying to figure out how a `react-meta` components would work. However the nesting would feel unnatural:

```xml
<DocumentMeta>
  <DocumentLink> 
    <DocumentTitle> 
      ...
   </DocumentTitle>
 </DocumentLink>
</DocumentMeta>
```

A `react-head` component was a nice idea, though it would duplicate react-document-title.

**Comment by gaearon** [comment]
Maybe I'm stretching it a bit too thin but you can combine these two right in your app.
For example

```
js
var MyAppMeta = React.createClass({
  var image = this.props.image;
  var title = this.props.title || '';

  if (title.length > 0) {
    title += ' * MyApp';
  }

  render() {
    return (
      <DocumentMeta meta={{ 'og:image': image, 'og:title': title }}>
        <DocumentTitle={title}>
          {this.props.children}
        </DocumentTitle>
      <DocumentMeta>
    };
  }
});
```

and use it throughout the app. This also has a nice effect of allowing to easily keep `og:title` synchronized with `title` without repetition & adding custom prefix or suffix to the title.

**Comment by gpbl** [comment]
I'd better add a `title` prop to a `DocumentHead` component using react-bubble :-)

A part from the module name, why do you think adding meta and links props would make the component more complicated?

```js
// DocumentHead.js
'use strict';

var React = require('react'),
    Children = require('react/addons').Children,
    PropTypes = React.PropTypes,
    BubbleMixin = require('./BubbleMixin');

var DocumentHead = React.createClass({
  displayName: 'DocumentHead',

  mixins: [BubbleMixin],

  statics: {
    rewind: function () {
      var activeInstance = this.getActiveInstance();
      this.clearMountedInstances();

      if (activeInstance) {
        return {
          title: activeInstance.props.title,
          meta: activeInstance.props.meta.map(function(props){
            return React.createElement('meta', props)
          }),
          link: activeInstance.props.link.map(function(props){
            return React.createElement('link', props)
          })
        }
      }
    }
  },

  propTypes: {
    title: PropTypes.string,
    meta: PropTypes.arrayOf(PropTypes.objectOf(PropTypes.string)),
    link: PropTypes.arrayOf(PropTypes.objectOf(PropTypes.string))
  },

  getDefaultProps: function () {
    return {
      title: '',
      meta: [],
      link: []
    };
  },

  performSideEffect: function () {
    var title = this.props.title;
    if (typeof document !== 'undefined' && title !== document.title) {
      document.title = title;
    }
  }
});

module.exports = DocumentHead;
```

```js
// Html.jsx
import DocumentHead from 'react-document-head';

const head = DocumentHead.rewind()

const markup = React.renderComponentToString('<MyApp />');

const Html = React.createClass({

  render() {
    return (
      <html>
        <head>      
          <title>{ head.title }</title>
          { head.meta }
          { head.link }
        </head>
        <body>
          <div id="mountNode" dangerouslySetInnerHTML={{__html: markup}} />
        </body>
      </html>
    );
  }

});

export default Html;
```

**Comment by Maximilianos** [comment]
+1 to this!

**Comment by doctyper** [comment]
+1!

**Comment by onemanstartup** [comment]
It reminds me this solution https://github.com/matthewwithanm/react-frozenhead

**Comment by gpbl** [comment]
Oh nice I like the idea of using children, @gaearon what do you think?

**Comment by gaearon** [comment]
I also like children more than properties. However that doesn't play with nesting. Say I want to define `<link rel='canonical'>` at the top, but want to override just title (or just meta) somewhere below? Or I have `<meta>` for every route, but want to have `title` depend on `state` somewhere deep inside?

The reason I'm not moving ahead with this, is I can't figure out the behavior that wouldn't jeopardize the nesting.

**Comment by gaearon** [comment]
I extracted [React Side Effect](https://github.com/gaearon/react-side-effect) from this project. It's now easy to use it to implement any kind of nesting logic for `<meta>` and other tags as a separate project from React Document Title, but also without overlapping too much.

I'll close this issue. Please let me know if you use React Side Effect to implement React Meta or event React Head which would supersede this project. I currently don't have interest in this, but React Side Effect should have you all set.

**Comment by gpbl** [comment]
:+1: great thank you!

**Comment by gpbl** [comment]
Follow up for those interested to add meta tags server-side :-) 

After reading [this discussion](https://github.com/gaearon/react-side-effect/pull/1) and lurking [the approach](https://github.com/skevy/react-document-meta) by @skevy, I am going for a simpler solution, skipping the nesting support. I believe `react-side-effect` does too much for the case of meta tags.

This is `HtmlHead.jsx`:

```js
import React from 'react';
let _head = '';
const HtmlHead = React.createClass({
  statics: {
    rewind() {
      return _head;
    }
  },
  componentWillMount() {
    const el = <head>{ this.props.children}</head>;
    _head = React.renderToStaticMarkup(el).replace(/<\/?head>/g, '');
  },
  render() { return null; }
});
export default HtmlHead;
```

which can be used **in the route handler** as:

```js
// HomePage.jsx
render() {
  return (
    <div>
      <HtmlHead>
        <meta name="description" content="Nice description" />
        <meta name="keyword" content="foo, bar" />
      </HtmlHead>
      <p>Welcome to the home page!</p>
    </div>
  );
}
```

Server-side we call `rewind()` to get the head content as string:

```js
import HtmlHead from 'HtmlHead.jsx';
// ...
const markup = React.renderToString(<RouteHandler />)
const head = HtmlHead.rewind();
let htmlEl = <Html head={head} markup={markup} />;
const html = React.renderToStaticMarkup(htmlEl);
res.send(html);
```

I'm not 100% sure if it is concurrency safe, though – @gaearon do you have a suggestion? Better clean the `_head` var in the `rewind()` or must the clean made server-side after calling `rewind()` ? need to make some tests...

**Comment by geekyme** [comment]
hello @gaearon I have something working here that uses react-side-effect. https://github.com/geekyme/react-doc-meta. Help needed to test it properly :)

**Comment by danieljuhl** [comment]
[boligbesked/react-document-meta]

@geekyme you beat me in time, but created something similar. It is a bit more strict but also a bit more flexible. I'll be creating tests and proper documentation within a week or two - but for now, the examples in the repo gives an idea of how to use it.

Main differences between `react-doc-meta` and `react-document-meta`, is that react-document-meta allows nesting/extending, so that you can create some base meta on the outer most level, and modify these as you progress down you components. Also `react-document-meta` has a different way of setting the meta data, and has some special root level attributes (`title`, `description` and `canonical`) which can be used for auto generation of eg. `og:url´-meta tag

**Comment by geekyme** [comment]
Ah great job. :) I'll just stick with mine for now since I'm already using it in production. Would love to get more help on making the simple library better & more reliable though!

**Comment by cwelch5** [comment]
Hey Everyone, the NFL just released this library, based off this great library!  https://github.com/nfl/react-helmet
This library works with isomorphic apps and let's you specify page title, meta & link tags in a nested fashion.
Thanks for checking it out!
