### ISSUE TITLE
Change to use a context instead of a static singleton

### ISSUE THREAD

**Issue by mtscout6** [gaearon/react-document-title#9]
I may be wrong but would the use of static [`mountedInstances`](https://github.com/gaearon/react-document-title/blob/master/index.js#L15) have potential issues on a server under load? Especially if your request does anything async (ie. request data from database). I could see some potential bleed over between requests.

**Comment by gaearon** [comment]
`React.renderToString()` is synchronous so even if folks fetch data it's not an issue.
See also #7
